exclude: _vendor|vendored
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.2.1
  hooks:
  - id: ruff
  - id: ruff-format
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.28.0
  hooks:
  - id: check-github-workflows
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  # .py files are skipped cause already checked by other hooks
  hooks:
  - id: check-yaml
  - id: check-toml
  - id: check-merge-conflict
    exclude: .*\.py
  - id: end-of-file-fixer
    exclude: .*\.py
  - id: trailing-whitespace
    # trailing whitespace has meaning in markdown https://www.markdownguide.org/hacks/#indent-tab
    exclude: .*\.py|.*\.md
  - id: mixed-line-ending
    exclude: .*\.py
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.8.0'  # Use the sha / tag you want to point at
  hooks:
  - id: mypy
